# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "ry-terraform-prac"
    dynamodb_table = "ry-terraform-prac"
    encrypt        = true
    key            = "002/workspaces/iam/terraform.tfstate"
    region         = "ap-southeast-1"
  }
}
