# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "ry-terraform-state-002-workspaces"
    dynamodb_table = "ry-terraform-state-locks-002-workspaces"
    encrypt        = true
    key            = "isolated/services/web-server/terraform.tfstate"
    region         = "us-east-1"
  }
}
