# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    key            = "003/web-server/terraform.tfstate"
    region         = "ap-southeast-1"
    bucket         = "ry-terraform-prac"
    dynamodb_table = "ry-terraform-prac"
    encrypt        = true
  }
}
